services:
  app-server:
    build: 
      dockerfile: Dockerfile
    image: result/latest
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      master-db-server:
        condition: service_healthy
        restart: true
    develop:
      watch:
        - action : sync
          path: .
          target: .
          
  master-db-server:
    image: postgres:17
    restart: always
    hostname: master-database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      # - container-base-storage:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - master-db-server
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
      - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIGURE_SERVER}
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=${PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED}
    ports:
      - "${PGADMIN_PORT}:80"
    restart: always
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
volumes:
  container-base-storage: {}